name: "MagicShuffle"
email: "MagicShuffle@example.com"
password: "MagicShuffle"
password_confirmation: "MagicShuffle"

twitter_consumer_key: "4xP4Mo8bJT3KRgIGeUzA"
twitter_consumer_secret: "4xrHalpZ8ud0fcbTvJcN3FC3z1GP8F2PlGu6uGxVE"

weibo_key: "679289252"
weibo_secret: "8e35ec77cabdfc89247ccbd0f8689050"