name: "MagicShuffle"
email: "MagicShuffle@example.com"
password: "MagicShuffle"
password_confirmation: "MagicShuffle"

twitter_consumer_key: "4xP4Mo8bJT3KRgIGeUzA"
twitter_consumer_secret: "4xrHalpZ8ud0fcbTvJcN3FC3z1GP8F2PlGu6uGxVE"

weibo_key: "2153127382"
weibo_secret: "71069a071f20dddec61261d2258e6d3c"